import localFont from "next/font/local";
import "./globals.css";

const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--font-roboto-regular",
  weight: "100 900",
});
const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoRegular.variable} ${poppinsRegular.variable} antialiased`}>
        <div
          id="root"
          className="flex flex-col items-center justify-start w-[100vw]"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
